In [1]:
import pandas as pd
import numpy as np

energy = pd.read_excel("Energy Indicators.xls")
energy = energy.drop('Unnamed: 0', axis=1)
energy = energy.drop('Unnamed: 1', axis=1)

energy.columns=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
# make sure to exclude the footer and header information from the datafile.
# energy.drop?

energy = energy.iloc[16:]

# reset the index start from 0
energy.reset_index(drop=True, inplace=True)

# Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule).
# For all countries which have missing data (e.g. data with "...") 
# make sure this is reflected as `np.NaN` values.
energy['Energy Supply'] = energy['Energy Supply'].map(lambda x: np.NaN if x=='...' else x*1000000)
energy[energy['Country'] == 'United Kingdom of Great Britain and Northern Ireland19']

# find the country  has number
change_mask = energy['Country'].str.contains(r'[0-9]+| [(,))]+', na=False)
energy[change_mask]

# here are also several countries with numbers and/or parenthesis in their name. Be sure to remove these
# 'Bolivia (Plurinational State of)' should be 'Bolivia',

# 'Switzerland17' should be 'Switzerland'.
energy['Country'] = energy['Country'].str.replace('[0-9]+|[(,)]+', '')
energy[change_mask]

# Rename the following list of countries (for use in later questions):
energy.replace({"Republic of Korea": "South Korea", 
                "United States of America": "United States",
                "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", 
                "China Hong Kong Special Administrative Region": "Hong Kong",
                "Iran Islamic Republic of": 'Iran'}, 
               inplace=True)

# check all have been changed
country_mask = energy['Country'].isin(['South Korea', "United States","United Kingdom", "Hong Kong"])
energy[country_mask]
# energy[energy['Country'] == 'Hong Kong']
#energy['Country'].iloc[235]

# load the GDP data from the file world_bank.csv,
# which is a csv containing countries' GDP from 1960 to 2015 from World Bank. 
# Call this DataFrame GDP
GDP = pd.read_csv('world_bank.csv')
# GDP.head()
GDP_country_list = list(GDP.iloc[3])
print(GDP_country_list)
GDP = GDP.iloc[4:]
#print(GDP.iloc[0])
GDP.columns = GDP_country_list
#print(GDP.iloc[0])

# rename these country
# "Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"
GDP['Country Name'].replace({"Korea, Rep.": "South Korea", 
                                                "Iran, Islamic Rep.": "Iran", 
                                                "Hong Kong SAR, China": "Hong Kong"}, 
                                              inplace=True)
# check all have been changed, test code
# GDP_country_mask = GDP['Country Name'].isin(['South Korea', "Iran", "Hong Kong"])
# GDP[GDP_country_mask]

# load the Sciamgo from the file scimagojr-3.xlsx,
# which ranks countries based on their journal contributions in the aforementioned area. 
# Call this DataFrame ScimEn.
ScimEn = pd.read_excel('scimagojr-3.xlsx')
ScimEn.head()
# get the top 15 country in ScimEn rank
rank_mask = ScimEn['Rank'] < 16
rank_country_name = list(ScimEn[rank_mask]['Country'])
print(rank_country_name)
ScimEn_rank = ScimEn[rank_mask]
ScimEn_rank.reset_index(drop=True, inplace=True)

energy_rank = energy[energy['Country'].isin(rank_country_name)]
energy_rank.reset_index(drop=True, inplace=True)

GDP_rank = GDP[GDP['Country Name'].isin(rank_country_name)]
GDP_rank.reset_index(drop=True, inplace=True)

# set GDP_rank column name to 'Country'
GDP_rank = GDP_rank.rename(columns={'Country Name': 'Country'})
print('GDP_rank columns: ' + str(list(GDP_rank.columns)))
# energy_rank
# find the missing country in energy is 'Iran Islamic Republic of'
# go backk to energy to rename it to Iran
#energy[energy['Country'].str.contains('Ir', na=False)]
#GDP_rank
#check
# ScimEn_rank
print(list(ScimEn_rank.columns))

all_rank = pd.merge(energy_rank, ScimEn_rank, how='right', left_on='Country', right_on='Country')
print(list(all_rank.columns))
all_rank = pd.merge(GDP_rank, all_rank, how='right', left_on='Country', right_on='Country')
print(list(all_rank.columns))
#all_rank

# The index of this DataFrame should be the name of the country, 
all_rank.set_index('Country', inplace=True)

# all_rank.set_index('')

# 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0
# they are <class 'numpy.float64'> which should make them to interger
for col in all_rank.columns:
    # print(str(type(col)) + '-\n')
    if type(col) == np.float64:
        all_rank.rename(columns={col: col.astype(int)}, inplace=True)
        #print('float64 to'+ str(type(col)))

print(list('change to int\n'))
print(list(all_rank.columns))

# the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 
# 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', 
#'2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015'].
all_rank_columns = ['Rank', 'Documents', 'Citable documents', 
                    'Citations', 'Self-citations', 'Citations per document', 
                    'H index', 'Energy Supply', 'Energy Supply per Capita', 
                    '% Renewable', 2006, 2007, 
                    2008, 2009, 2010, 
                    2011, 2012, 2013, 
                    2014, 2015]
# note that the column about year is type int, so the all_rank_columns list should be int
all_rank15 = all_rank[all_rank_columns]


def answer_one():
    return all_rank15

answer_one()

['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', 1960.0, 1961.0, 1962.0, 1963.0, 1964.0, 1965.0, 1966.0, 1967.0, 1968.0, 1969.0, 1970.0, 1971.0, 1972.0, 1973.0, 1974.0, 1975.0, 1976.0, 1977.0, 1978.0, 1979.0, 1980.0, 1981.0, 1982.0, 1983.0, 1984.0, 1985.0, 1986.0, 1987.0, 1988.0, 1989.0, 1990.0, 1991.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0]
['China', 'United States', 'Japan', 'United Kingdom', 'Russian Federation', 'Canada', 'Germany', 'India', 'France', 'South Korea', 'Italy', 'Spain', 'Iran', 'Australia', 'Brazil']
GDP_rank columns: ['Country', 'Country Code', 'Indicator Name', 'Indicator Code', 1960.0, 1961.0, 1962.0, 1963.0, 1964.0, 1965.0, 1966.0, 1967.0, 1968.0, 1969.0, 1970.0, 1971.0, 1972.0, 1973.0, 1974.0, 1975.0, 1976.0, 1977.0, 1978.0, 1979.0, 1980.0, 1981.0, 1982.0, 1983.0, 1984.0, 1985.0, 1986.0, 1987.0, 1988.0, 1989.0, 1990.0, 1991.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0]
['Rank', 'Country', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index']
['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', 'Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index']
['Country', 'Country Code', 'Indicator Name', 'Indicator Code', 1960.0, 1961.0, 1962.0, 1963.0, 1964.0, 1965.0, 1966.0, 1967.0, 1968.0, 1969.0, 1970.0, 1971.0, 1972.0, 1973.0, 1974.0, 1975.0, 1976.0, 1977.0, 1978.0, 1979.0, 1980.0, 1981.0, 1982.0, 1983.0, 1984.0, 1985.0, 1986.0, 1987.0, 1988.0, 1989.0, 1990.0, 1991.0, 1992.0, 1993.0, 1994.0, 1995.0, 1996.0, 1997.0, 1998.0, 1999.0, 2000.0, 2001.0, 2002.0, 2003.0, 2004.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 'Energy Supply', 'Energy Supply per Capita', '% Renewable', 'Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index']
['c', 'h', 'a', 'n', 'g', 'e', ' ', 't', 'o', ' ', 'i', 'n', 't', '\n']
['Country Code', 'Indicator Name', 'Indicator Code', 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 'Energy Supply', 'Energy Supply per Capita', '% Renewable', 'Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index']

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13

In [2]:
# When you joined the datasets, 
# but before you reduced this to the top 15 items, how many entries did you lose?
%%HTML
<svg width="800" height="300">
  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="blue" />
  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="red" />
  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="green" />
  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>
  <text  x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>
</svg>

In [10]:
def answer_two():
    return len(energy) + len(GDP) + len(ScimEn) - 3 * len(all_rank15)

answer_two()

675

In [4]:
# What is the average GDP over the last 10 years for each country? 
# (exclude missing values from this calculation.)
# heir average GDP sorted in descending order.
all_rank_years_columns = [2006, 2007, 
                    2008, 2009, 2010, 
                    2011, 2012, 2013, 
                    2014, 2015]
def answer_three():
    Top15 = answer_one()
    Top15['average GDP'] = Top15[all_rank_years_columns].mean(1)
    Top15.sort_index(by='average GDP', ascending=False, inplace=True)
    return Top15
answer_three()

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  # This is added back by InteractiveShellApp.init_path()
C:\Anaconda3\lib\site-packages\pandas\core\frame.py:4452: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  inplace=inplace)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,average GDP
Country,,,,,,,,,,,,,,,,,,,,,
United States,2,96661,94747,792274,265436,8.20,230,0.090838,286,11.570980,...,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,1.536434e+13
China,1,127050,126767,597237,411683,4.70,138,0.127191,93,19.754910,...,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,6.348609e+12
Japan,3,30504,30287,223024,61554,7.31,134,0.018984,149,10.232820,...,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,5.542208e+12
Germany,7,17027,16831,140566,27426,8.26,126,0.013261,165,17.901530,...,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,3.493025e+12
France,9,13153,12973,130632,28601,9.93,114,0.010597,166,17.020280,...,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,2.681725e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,0.007920,124,10.600470,...,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,2.487907e+12
Brazil,15,8668,8596,60702,14396,7.00,86,0.012149,59,69.648030,...,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,2.189794e+12
Italy,11,10964,10794,111850,26661,10.20,106,0.006530,109,33.667230,...,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,2.120175e+12
India,8,15005,14841,128763,37209,8.58,115,0.033195,26,14.969080,...,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,1.769297e+12
Canada,6,17899,17620,215003,40930,12.01,149,0.010431,296,61.945430,...,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,1.660647e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,0.030709,214,17.288680,...,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,1.565459e+12
Spain,12,9428,9330,123336,23964,13.08,115,0.004923,106,37.968590,...,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,1.418078e+12
Australia,14,8831,8725,90765,15606,10.28,107,0.005386,231,11.810810,...,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,1.164043e+12
South Korea,10,11983,11923,114675,22595,9.57,104,0.011007,221,2.279353,...,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,1.106715e+12
Iran,13,8896,8819,57470,19125,6.46,72,0.009172,119,5.707721,...,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,4.441558e+11

In [5]:
# By how much had the GDP changed over the 10 year span 
# for the country with the 6th largest average GDP?
def answer_four():
    Top15 = answer_three()
    Top6 = Top15.iloc[:5]
    Top6['GDP_span'] = Top6[2015] - Top6[2006]
    return Top6
answer_four()

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  # This is added back by InteractiveShellApp.init_path()
C:\Anaconda3\lib\site-packages\pandas\core\frame.py:4452: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  inplace=inplace)
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2008,2009,2010,2011,2012,2013,2014,2015,average GDP,GDP_span
Country,,,,,,,,,,,,,,,,,,,,,
United States,2,96661,94747,792274,265436,8.20,230,0.090838,286,11.57098,...,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,1.536434e+13,1.756269e+12
China,1,127050,126767,597237,411683,4.70,138,0.127191,93,19.75491,...,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,6.348609e+12,4.805667e+12
Japan,3,30504,30287,223024,61554,7.31,134,0.018984,149,10.23282,...,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,5.542208e+12,1.730216e+11
Germany,7,17027,16831,140566,27426,8.26,126,0.013261,165,17.90153,...,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,3.493025e+12,3.526652e+11
France,9,13153,12973,130632,28601,9.93,114,0.010597,166,17.02028,...,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,2.681725e+12,1.533457e+11

In [3]:
#What is the mean Energy Supply per Capita?
def answer_five():
    Top15 = answer_one()
    return Top15['Energy Supply per Capita'].mean()

answer_five()

157.6

In [14]:
# What country has the maximum % Renewable and what is the percentage?

# This function should return a tuple with the name of the country and the percentage.
def answer_six():
    Top15 = answer_one()
    max_num = Top15['% Renewable'].max()
    Country_num = Top15[Top15['% Renewable'] == max_num].index[0]
    return (Country_num, max_num)

answer_six()

('Brazil', 69.64803)

In [9]:
# Question 7 (6.6%)
# Create a new column that is the ratio of Self-Citations to Total Citations. 
# What is the maximum value for this new column, and what country has the highest ratio?
# This function should return a tuple with the name of the country and the ratio.
def answer_seven():
    Top15 = answer_one()
    print(list(Top15.columns))
    Top15['ratio'] = Top15['Self-citations'] / Top15['Citations']
    max_ratio = Top15['ratio'].max()
    print(max_ratio)
    max_s = Top15[Top15['ratio'] == max_ratio]
    return (max_s.index[0], max_ratio)

answer_seven()

['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 'ratio']
0.6893126179389422

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

('China', 0.6893126179389422)

In [24]:
# Question 8 (6.6%)
# Create a column that estimates the population using Energy Supply 
# and Energy Supply per capita. What is the third most populous country according to this estimate?

# This function should return a single string value.
def answer_eight():
    Top15 = answer_one()
    # print(Top15.columns)
    Top15['population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    
    Top15.sort_index(by='population', inplace=True, ascending=False)
    #print(Top15.head())
    #print(type(Top15.iloc[2]))
    
    # Top15.iloc[2] would return all the velue in index 2 but not the object of serie 2
    return Top15.index.tolist()[2]

answer_eight()

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  # This is added back by InteractiveShellApp.init_path()
C:\Anaconda3\lib\site-packages\pandas\core\frame.py:4452: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  inplace=inplace)

'United States'

In [54]:
    Top15 = answer_one()
    #print(list(Top15.columns))
    Top15['population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['citable documents per capita'] = Top15['Citable documents'] / Top15['population'] 
    # print(Top15.head())
    #print(list(Top15.columns))
    corr_df = Top15[['citable documents per capita', 'Energy Supply per Capita']]

    type(corr_df['citable documents per capita'])

    data=pd.DataFrame([[-2.1,-1,4.3],[3,1.1,0.12],[3,1.1,0.12]],index=['one','two','three'],columns=list('abc'))
    data.corr()
    corr_df.corr()
    
    df = pd.DataFrame({'A':np.random.randint(1, 100, 10),
     'B':np.random.randint(1, 100, 10)})
    df.corr()

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

          A         B
A  1.000000 -0.093126
B -0.093126  1.000000

In [56]:
# Question 9 (6.6%)¶
# Create a column that estimates the number of citable documents per person. 
# What is the correlation between the number of citable documents per capita and 
# the energy supply per capita? Use the .corr() method, (Pearson's correlation).

# This function should return a single number.

# (Optional: Use the built-in function plot9() to visualize the relationship 
# between Energy Supply per Capita vs. Citable docs per Capita)
def answer_nine():
    Top15 = answer_one()
    #print(list(Top15.columns))
    Top15['population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['citable documents per capita'] = Top15['Citable documents'] / Top15['population'] 
    # print(Top15.head())
    #print(list(Top15.columns))
    corr_df = Top15[['Energy Supply per Capita', 'citable documents per capita']]
    #corr_df = Top15[['Energy Supply per Capita', 'Citable documents']]
    print(corr_df.head())
    print(corr_df.corr())
    df = corr_df.corr()
    return df

answer_nine().head()

                   Energy Supply per Capita citable documents per capita
Country
China                                    93                    9.269e-05
India                                    26                  1.16242e-05
United States                           286                  0.000298307
Brazil                                   59                  4.17453e-05
Russian Federation                      214                  0.000127533
Empty DataFrame
Columns: []
Index: []

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Empty DataFrame
Columns: []
Index: []

In [57]:
def plot9():
    import matplotlib as plt
    %matplotlib inline
    
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])
    
plot9()

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

ValueError: scatter requires x column to be numeric

In [74]:
# Create a new column with a 1 if the country's % Renewable value is at or above the median 
# for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

# This function should return a series named HighRenew 
# whose index is the country name sorted in ascending order of rank.
def answer_ten():
    Top15 = answer_one()
#    print(list(Top15.columns))
    median = Top15['% Renewable'].median()
    Top15['HighRenew'] = Top15['% Renewable'].map(lambda x: 1 if (x > median) else 0)
    Top15.sort_index(by='Rank', ascending=True, inplace=True)
#    print(Top15)
    return Top15['HighRenew']

answer_ten()

['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 'population', 'citable documents per capita', 'PopEst', 'Citable docs per Capita', 'HighRenew']
                    Rank  Documents  Citable documents  Citations  \
Country
China                  1     127050             126767     597237
United States          2      96661              94747     792274
Japan                  3      30504              30287     223024
United Kingdom         4      20944              20357     206091
Russian Federation     5      18534              18301      34266
Canada                 6      17899              17620     215003
Germany                7      17027              16831     140566
India                  8      15005              14841     128763
France                 9      13153              12973     130632
South Korea           10      11983              11923     114675
Italy                 11      10964              10794     111850
Spain                 12       9428               9330     123336
Iran                  13       8896               8819      57470
Australia             14       8831               8725      90765
Brazil                15       8668               8596      60702

                    Self-citations  Citations per document  H index  \
Country
China                       411683                    4.70      138
United States               265436                    8.20      230
Japan                        61554                    7.31      134
United Kingdom               37874                    9.84      139
Russian Federation           12422                    1.85       57
Canada                       40930                   12.01      149
Germany                      27426                    8.26      126
India                        37209                    8.58      115
France                       28601                    9.93      114
South Korea                  22595                    9.57      104
Italy                        26661                   10.20      106
Spain                        23964                   13.08      115
Iran                         19125                    6.46       72
Australia                    15606                   10.28      107
Brazil                       14396                    7.00       86

                    Energy Supply Energy Supply per Capita  % Renewable  \
Country
China                1.271910e+11                       93    19.754910
United States        9.083800e+10                      286    11.570980
Japan                1.898400e+10                      149    10.232820
United Kingdom       7.920000e+09                      124    10.600470
Russian Federation   3.070900e+10                      214    17.288680
Canada               1.043100e+10                      296    61.945430
Germany              1.326100e+10                      165    17.901530
India                3.319500e+10                       26    14.969080
France               1.059700e+10                      166    17.020280
South Korea          1.100700e+10                      221     2.279353
Italy                6.530000e+09                      109    33.667230
Spain                4.923000e+09                      106    37.968590
Iran                 9.172000e+09                      119     5.707721
Australia            5.386000e+09                      231    11.810810
Brazil               1.214900e+10                       59    69.648030

                      ...              2011          2012          2013  \
Country               ...
China                 ...      6.612490e+12  7.124978e+12  7.672448e+12
United States         ...      1.520402e+13  1.554216e+13  1.577367e+13
Japan                 ...      5.473738e+12  5.569102e+12  5.644659e+12
United Kingdom        ...      2.450911e+12  2.479809e+12  2.533370e+12
Russian Federation    ...      1.589943e+12  1.645876e+12  1.666934e+12
Canada                ...      1.664087e+12  1.693133e+12  1.730688e+12
Germany               ...      3.542371e+12  3.556724e+12  3.567317e+12
India                 ...      1.821872e+12  1.924235e+12  2.051982e+12
France                ...      2.702032e+12  2.706968e+12  2.722567e+12
South Korea           ...      1.134796e+12  1.160809e+12  1.194429e+12
Italy                 ...      2.137439e+12  2.077184e+12  2.040871e+12
Spain                 ...      1.417355e+12  1.380216e+12  1.357139e+12
Iran                  ...      4.853309e+11  4.532569e+11  4.445926e+11
Australia             ...      1.169431e+12  1.211913e+12  1.241484e+12
Brazil                ...      2.295245e+12  2.339209e+12  2.409740e+12

                            2014          2015   population  \
Country
China               8.230121e+12  8.797999e+12  1.36765e+09
United States       1.615662e+13  1.654857e+13  3.17615e+08
Japan               5.642884e+12  5.669563e+12  1.27409e+08
United Kingdom      2.605643e+12  2.666333e+12   6.3871e+07
Russian Federation  1.678709e+12  1.616149e+12    1.435e+08
Canada              1.773486e+12  1.792609e+12  3.52399e+07
Germany             3.624386e+12  3.685556e+12  8.03697e+07
India               2.200617e+12  2.367206e+12  1.27673e+09
France              2.729632e+12  2.761185e+12  6.38373e+07
South Korea         1.234340e+12  1.266580e+12  4.98054e+07
Italy               2.033868e+12  2.049316e+12  5.99083e+07
Spain               1.375605e+12  1.419821e+12  4.64434e+07
Iran                4.639027e+11           NaN  7.70756e+07
Australia           1.272520e+12  1.301251e+12   2.3316e+07
Brazil              2.412231e+12  2.319423e+12  2.05915e+08

                    citable documents per capita       PopEst  \
Country
China                                  9.269e-05  1.36765e+09
United States                        0.000298307  3.17615e+08
Japan                                0.000237714  1.27409e+08
United Kingdom                       0.000318721   6.3871e+07
Russian Federation                   0.000127533    1.435e+08
Canada                               0.000500002  3.52399e+07
Germany                               0.00020942  8.03697e+07
India                                1.16242e-05  1.27673e+09
France                                0.00020322  6.38373e+07
South Korea                          0.000239392  4.98054e+07
Italy                                0.000180175  5.99083e+07
Spain                                 0.00020089  4.64434e+07
Iran                                  0.00011442  7.70756e+07
Australia                            0.000374206   2.3316e+07
Brazil                               4.17453e-05  2.05915e+08

                    Citable docs per Capita  HighRenew
Country
China                             9.269e-05          1
United States                   0.000298307          0
Japan                           0.000237714          0
United Kingdom                  0.000318721          0
Russian Federation              0.000127533          1
Canada                          0.000500002          1
Germany                          0.00020942          1
India                           1.16242e-05          0
France                           0.00020322          0
South Korea                     0.000239392          0
Italy                           0.000180175          1
Spain                            0.00020089          1
Iran                             0.00011442          0
Australia                       0.000374206          0
Brazil                          4.17453e-05          1

[15 rows x 25 columns]

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)
  # This is added back by InteractiveShellApp.init_path()
C:\Anaconda3\lib\site-packages\pandas\core\frame.py:4452: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  inplace=inplace)

Country
China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    1
Canada                1
Germany               1
India                 0
France                0
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: HighRenew, dtype: int64

In [72]:
# Question 11 (6.6%)¶
# Use the following dictionary to group the Countries by Continent, 
# then create a dateframe that displays the sample size (the number of countries in each continent bin), 
# and the sum, mean, and std deviation for the estimated population of each country.

''' ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
'''
# This function should return a DataFrame with index named Continent 
# ['Asia', 'Australia', 'Europe', 'North America', 'South America'] 
# and columns ['size', 'sum', 'mean', 'std']
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}

def answer_eleven():
    Top15 = answer_one()
    Top15.groupby(ContinentDict)
    
    Top15 = answer_one()
    Top15['est_pop'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']

    # ！！！！！！！！！！！！！！！！！！！！！！！
    # 'est_pop' is <class 'float'> which could not be average in agg
    # 'Energy Supply' is <class 'numpy.float64'>
    print(type(Top15['est_pop'][0]))
    print(type(Top15['Energy Supply'][0]))
    print('------------------')
    Top15['est_pop'] = Top15['est_pop'].astype('float64')
    print(type(Top15['est_pop'][0]))
    # Top15['est_pop'].mean() this work

    #Top15['est_pop'].head
    new_top = Top15.groupby(ContinentDict)['est_pop'].agg({'size': 'count', 'sum': np.sum, 'mean':np.average, 'std':np.std})
    # (Top15.groupby(ContinentDict)['est_pop'].agg({'mean':np.average}))
    #Top15.groupby(ContinentDict)['est_pop'].mean()
    return new_top
answer_eleven()

<class 'float'>
<class 'numpy.float64'>
------------------
<class 'numpy.float64'>

C:\anaconda3\lib\site-packages\ipykernel_launcher.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\anaconda3\lib\site-packages\ipykernel_launcher.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\anaconda3\lib\site-packages\ipykernel_launcher.py:59: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version

               size           sum          mean           std
Asia              5  2.898666e+09  5.797333e+08  6.790979e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            6  4.579297e+08  7.632161e+07  3.464767e+07
North America     2  3.528552e+08  1.764276e+08  1.996696e+08
South America     1  2.059153e+08  2.059153e+08           NaN

In [84]:
# Question 12 (6.6%)
# Cut % Renewable into 5 bins. Group Top15 by the Continent, 
# as well as these new % Renewable bins. 
# How many countries are in each of these groups?

# This function should return a Series with a MultiIndex of Continent,
# then the bins for % Renewable.
# Do not include groups with no countries.
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
def answer_twelve():
    Top15 = answer_one()
    pd.cut(Top15['% Renewable'], 5)
    top_group = Top15.groupby([ContinentDict, '% Renewable'])
    return top_group.size()

#answer_twelve()
Top15 = answer_one()
Top15['% Renewable Cut5'] = pd.cut(Top15['% Renewable'], 5)
Top15.groupby([ContinentDict, '% Renewable Cut5']).size()

C:\anaconda3\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

               % Renewable Cut5
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
Australia      (2.212, 15.753]     1
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
North America  (2.212, 15.753]     1
               (56.174, 69.648]    1
South America  (56.174, 69.648]    1
dtype: int64

In [5]:
# Question 13 (6.6%)
# Convert the Population Estimate series to a string with thousands separator (using commas). Do not round the results.

# e.g. 317615384.61538464 -> 317,615,384.61538464

# This function should return a Series PopEst whose index is the country name and whose values are the population estimate string.

def thousands_separator(x):
    print("%d / 1000 = %d"%(x, x/1000))
    str_x = str(x)
    return str(x)
    

def answer_thirteen():
    Top15 = answer_one()
    Top15['est_pop'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']

    # ！！！！！！！！！！！！！！！！！！！！！！！
    # 'est_pop' is <class 'float'> which could not be average in agg
    # 'Energy Supply' is <class 'numpy.float64'>
    Top15['est_pop'] = Top15['est_pop'].astype('float64')
    print(type(Top15['est_pop']))
    Top15['est_pop_str'] = Top15['est_pop'].map(thousands_separator)
    
    return  Top15['est_pop_str']

est_pop = answer_thirteen()

print(type(est_pop[0]))
est_pop.head()

<class 'pandas.core.series.Series'>
23316017 // 1000 = 23316
205915254 // 1000 = 205915
35239864 // 1000 = 35239
1367645161 // 1000 = 1367645
80369696 // 1000 = 80369
46443396 // 1000 = 46443
63837349 // 1000 = 63837
63870967 // 1000 = 63870
1276730769 // 1000 = 1276730
77075630 // 1000 = 77075
59908256 // 1000 = 59908
127409395 // 1000 = 127409
49805429 // 1000 = 49805
143500000 // 1000 = 143500
317615384 // 1000 = 317615
<class 'str'>

C:\anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Country
Australia    23316017.316017315
Brazil       205915254.23728815
Canada        35239864.86486486
China        1367645161.2903225
Germany       80369696.96969697
Name: est_pop_str, dtype: object